const PUBLIC_UI_PROTOCOL = process.env.PUBLIC_UI_PROTOCOL;
const PUBLIC_UI_HOSTNAME = process.env.PUBLIC_UI_HOSTNAME;
const PUBLIC_UI_PORT = process.env.PUBLIC_UI_PORT;

const  PUBLIC_UI_ORIGIN =     `${PUBLIC_UI_PROTOCOL}://${PUBLIC_UI_HOSTNAME}${
      PUBLIC_UI_PORT === "80" ? "" : ":" + PUBLIC_UI_PORT
    }`;

const PUBLIC_SERVER_PROTOCOL = process.env.PUBLIC_SERVER_PROTOCOL;
const PUBLIC_SERVER_HOSTNAME = process.env.PUBLIC_SERVER_HOSTNAME;
const PUBLIC_SERVER_PORT = process.env.PUBLIC_SERVER_PORT;

const  PUBLIC_SERVER_ORIGIN =     `${PUBLIC_SERVER_PROTOCOL}://${PUBLIC_SERVER_HOSTNAME}${
      PUBLIC_SERVER_PORT === "80" ? "" : ":" + PUBLIC_SERVER_PORT
    }`;


const PUBLIC_LIVE_PROTOCOL = process.env.PUBLIC_LIVE_PROTOCOL;
const PUBLIC_LIVE_HOSTNAME = process.env.PUBLIC_LIVE_HOSTNAME;
const PUBLIC_LIVE_PORT = process.env.PUBLIC_LIVE_PORT;

const  PUBLIC_LIVE_ORIGIN =     `${PUBLIC_LIVE_PROTOCOL}://${PUBLIC_LIVE_HOSTNAME}${
      PUBLIC_LIVE_PORT === "80" ? "" : ":" + PUBLIC_LIVE_PORT
    }`;


const PUBLIC_ETH_NODE_PROTOCOL = process.env.PUBLIC_ETH_NODE_PROTOCOL;
const PUBLIC_ETH_NODE_HOSTNAME = process.env.PUBLIC_ETH_NODE_HOSTNAME;
const PUBLIC_ETH_NODE_PORT = process.env.PUBLIC_ETH_NODE_PORT;

const  PUBLIC_ETH_NODE_ORIGIN =     `${PUBLIC_ETH_NODE_PROTOCOL}://${PUBLIC_ETH_NODE_HOSTNAME}${
      PUBLIC_ETH_NODE_PORT === "80" ? "" : ":" + PUBLIC_ETH_NODE_PORT
    }`;


console.log(
  PUBLIC_UI_ORIGIN,
  PUBLIC_SERVER_ORIGIN,
  PUBLIC_LIVE_ORIGIN,
  PUBLIC_ETH_NODE_ORIGIN
);

export {
  PUBLIC_UI_ORIGIN,
  PUBLIC_SERVER_ORIGIN,
  PUBLIC_LIVE_ORIGIN,
  PUBLIC_ETH_NODE_ORIGIN
}
