const PUBLIC_SERVER_SECURE = process.env.PUBLIC_SERVER_SECURE;
const PUBLIC_SERVER_HOSTNAME = process.env.PUBLIC_SERVER_HOSTNAME;
const PUBLIC_SERVER_PORT = process.env.PUBLIC_SERVER_PORT || 80;

const PUBLIC_SERVER_URL = `http${PUBLIC_SERVER_SECURE?"s":""}://${PUBLIC_SERVER_HOSTNAME}:${PUBLIC_SERVER_PORT}`

export {
  PUBLIC_SERVER_URL
}
